# ----------------------
# docker-compose.oneshot.yml
# ----------------------
version: '3.8'

services:
  mapstitcher:
    container_name: mapstitcher_service
    build:
      context: .
      dockerfile: Dockerfile_deploy
    image: mapstitcher:latest
    runtime: nvidia
    environment:
      - MATCHING_ALGORITHM=loftr
      - VRAM_SIZE=8.0
      - OUTPUT_FILE=stitched.jp2
    volumes:
      - /host_input:/data  # !adjust!
      - /host_output:/output  # !adjust!
    entrypoint: [ "/app/entrypoint_oneshot.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: no
