# ----------------------
# docker-compose.yml
# ----------------------
version: '3.8'

services:
  mapstitcher:
    container_name: mapstitcher
    build:
      context: .
      dockerfile: Dockerfile_deploy
      args:
        - TAG=v0.0.1
    image: mapstitcher:latest
    runtime: nvidia
    environment:
      - MATCHING_ALGORITHM=loftr
      - VRAM_SIZE=8.0
      - OUTPUT_FILE=stitched.jp2
    volumes:
      - ./host_input:/data  # !adjust!
      - ./host_output:/output  # !adjust!
    entrypoint: [ "/app/entrypoint_oneshot.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: no


  mapstitcher_service:
    container_name: mapstitcher_service
    image: mapstitcher:latest
    runtime: nvidia
    environment:
      - MATCHING_ALGORITHM=loftr
      - VRAM_SIZE=8.0
      - OUTPUT_FILE=stitched.jp2
    volumes:
      - ./host_input:/data  # !adjust!
      - ./host_output:/output  # !adjust!
    entrypoint: [ "/app/entrypoint_service.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: no
